[project]
name = "synapsteward-hue-alerts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nats-py>=2.10.0",
    "pydantic>=2.10.6",
    "requests>=2.32.3",
]
